### ISSUE TITLE
3proxy

### ISSUE THREAD

**Issue by Zyamstein** [khmyznikov/khmyznikov.github.io#1]
привет, примерно год назад ты на 3proxy боролся с проблемой обрезания скорости через 3proxy, каких-то положительных результатов добился?

**Comment by khmyznikov** [comment]
Честно уже не могу вспомнить, работает как-то) попробую конфиги глянуть может что-то есть интересное, отпишусь на днях, напомни если что.

**Comment by khmyznikov** [comment]
@Zyamstein не вижу ничего такого, скорее всего я просто забил. Использую его только для некоторых программ, весь трафик не пропускаю.
